#!/usr/bin/env node
/**
 * Packages the Vite build output into an ESA Edge Routine JS_AND_ASSETS zip:
 *
 *   routine/index.js   <- thin wrapper re-exporting the SSR server bundle
 *   routine/assets/    <- SSR server bundle chunks (dist/server/assets)
 *   assets/            <- client build artifacts (dist/client)
 *
 * Usage: node scripts/esa-package.mjs [routineName]
 * Output: esa/<routineName>.zip
 */
import { createWriteStream, existsSync } from 'node:fs'
import { cp, mkdir, readdir, rm, stat } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import JSZip from 'jszip'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const DIST_CLIENT = path.join(ROOT, 'dist', 'client')
const DIST_SERVER = path.join(ROOT, 'dist', 'server')
const SERVER_ENTRY = path.join(DIST_SERVER, 'server.js')
const STAGING_DIR = path.join(ROOT, 'esa', '.staging')
const ROUTINE_NAME = process.argv[2] || 'xhs-content-workflow'
const OUTPUT_ZIP = path.join(ROOT, 'esa', `${ROUTINE_NAME}.zip`)

const EXCLUDED_SERVER_FILES = new Set(['.dev.vars', 'wrangler.json', 'wrangler.jsonc'])

async function ensureDir(dir) {
  await mkdir(dir, { recursive: true })
}

async function assertBuildOutput() {
  const missing = []
  // SSR apps render HTML on the server, so the client output only carries
  // hashed assets + public files — require either index.html or assets/.
  if (
    !existsSync(path.join(DIST_CLIENT, 'index.html'))
    && !existsSync(path.join(DIST_CLIENT, 'assets'))
  ) {
    missing.push(DIST_CLIENT)
  }
  if (!existsSync(SERVER_ENTRY)) missing.push(SERVER_ENTRY)
  if (missing.length > 0) {
    console.error('[esa-package] Missing build output:', missing.join(', '))
    console.error('[esa-package] Run `bun run build` (vite build) before packaging.')
    process.exit(1)
  }
}

async function stageRoutine() {
  const routineDir = path.join(STAGING_DIR, 'routine')
  await ensureDir(routineDir)

  // Thin ESA Edge Routine entry: re-exports the platform-agnostic SSR handler.
  // The SSR bundle keeps its original `server.js` filename because shared
  // chunks back-reference it as `../server.js`.
  const wrapperSource = [
    '// Generated by scripts/esa-package.mjs — ESA Edge Routine entry.',
    "import app from './server.js'",
    '',
    'export default {',
    '  async fetch(request, env) {',
    '    return app.fetch(request, env)',
    '  },',
    '}',
    '',
  ].join('\n')
  await (await import('node:fs/promises')).writeFile(path.join(routineDir, 'index.js'), wrapperSource)

  // SSR bundle entry + shared chunks keep their relative layout so all
  // relative imports between entry and chunks still resolve.
  await cp(SERVER_ENTRY, path.join(routineDir, 'server.js'))
  const serverAssets = path.join(DIST_SERVER, 'assets')
  if (existsSync(serverAssets)) {
    await cp(serverAssets, path.join(routineDir, 'assets'), { recursive: true })
  }
}

async function stageClientAssets() {
  const assetsDir = path.join(STAGING_DIR, 'assets')
  await ensureDir(assetsDir)
  const entries = await readdir(DIST_CLIENT, { withFileTypes: true })
  for (const entry of entries) {
    if (entry.name.startsWith('.') || EXCLUDED_SERVER_FILES.has(entry.name)) continue
    await cp(
      path.join(DIST_CLIENT, entry.name),
      path.join(assetsDir, entry.name),
      { recursive: entry.isDirectory() },
    )
  }
}

async function totalSize(dir) {
  let total = 0
  const entries = await readdir(dir, { withFileTypes: true, recursive: true })
  for (const entry of entries) {
    if (!entry.isFile()) continue
    const fileStat = await stat(path.join(entry.parentPath ?? entry.path, entry.name))
    total += fileStat.size
  }
  return total
}

async function zipStaging() {
  const zip = new JSZip()
  const entries = await readdir(STAGING_DIR, { withFileTypes: true, recursive: true })
  for (const entry of entries) {
    if (!entry.isFile()) continue
    const absolute = path.join(entry.parentPath ?? entry.path, entry.name)
    const relative = path.relative(STAGING_DIR, absolute).split(path.sep).join('/')
    zip.file(relative, await (await import('node:fs/promises')).readFile(absolute))
  }
  await ensureDir(path.dirname(OUTPUT_ZIP))
  const buffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })
  await new Promise((resolve, reject) => {
    const stream = createWriteStream(OUTPUT_ZIP)
    stream.on('finish', resolve)
    stream.on('error', reject)
    stream.end(buffer)
  })
  return buffer.byteLength
}

async function main() {
  await assertBuildOutput()
  if (existsSync(STAGING_DIR)) await rm(STAGING_DIR, { recursive: true, force: true })

  await stageRoutine()
  await stageClientAssets()

  const routineSize = await totalSize(path.join(STAGING_DIR, 'routine'))
  const assetsSize = await totalSize(path.join(STAGING_DIR, 'assets'))
  const zipSize = await zipStaging()

  const mb = (bytes) => `${(bytes / (1024 * 1024)).toFixed(2)} MB`
  console.log('[esa-package] Routine name      :', ROUTINE_NAME)
  console.log('[esa-package] routine/ size     :', mb(routineSize), routineSize > 5 * 1024 * 1024 ? '(WARNING: > 5MB ER limit)' : '(within 5MB ER limit)')
  console.log('[esa-package] assets/ size      :', mb(assetsSize))
  console.log('[esa-package] Zip package       :', path.relative(ROOT, OUTPUT_ZIP), `(${mb(zipSize)})`)
  console.log('[esa-package] Staging preserved :', path.relative(ROOT, STAGING_DIR))
}

main().catch((error) => {
  console.error('[esa-package] Failed:', error)
  process.exit(1)
})
